unpackaged/pre/objects/Element__c/Element__c.object-meta.xml
<CustomObject>
    <label>Element</label>
    <nameField>
        <label>Element Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Elements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Element__c/fields/Page__c.field-meta.xml
<CustomField>
    <fullName>Page__c</fullName>
    <label>Page</label>
    <referenceTo>Page__c</referenceTo>
    <relationshipLabel>Elements</relationshipLabel>
    <relationshipName>Elements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Element__c/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <label>Sequence</label>
    <type>Number</type>
    <precision>18</precision>
    <scale>0</scale>
</CustomField>

force-app/main/default/objects/Element__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>rating</fullName>
            </value>
            <value>
                <fullName>dropdown</fullName>
            </value>
            <value>
                <fullName>comment</fullName>
            </value>
            <value>
                <fullName>checkbox</fullName>
            </value>
            <value>
                <fullName>boolean</fullName>
            </value>
            <value>
                <fullName>radiogroup</fullName>
            </value>
            <value>
                <fullName>text</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Page__c/Page__c.object-meta.xml
<CustomObject>
    <label>Page</label>
    <nameField>
        <label>Page Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Page__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <defaultValue>&quot;{}&quot;</defaultValue>
    <label>Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/pre/classes/ElementModel.cls
public class ElementModel {
    @AuraEnabled public Id id { get; set; }
    @AuraEnabled public Id pageId { get; set; }
    @AuraEnabled public String name { get; set; }
    @AuraEnabled public String type { get; set; }
    @AuraEnabled public Decimal sequence { get; set; }
    @AuraEnabled public String body { get; set; }
    
    // Additional fields from the JSON structure
    @AuraEnabled public Boolean startWithNewLine { get; set; }
    @AuraEnabled public Map<String, String> title { get; set; }
    @AuraEnabled public Integer rateCount { get; set; }
    @AuraEnabled public Integer rateMin { get; set; }
    @AuraEnabled public Integer rateMax { get; set; }
    @AuraEnabled public Map<String, String> minRateDescription { get; set; }
    @AuraEnabled public Map<String, String> maxRateDescription { get; set; }
    @AuraEnabled public String rateDescriptionLocation { get; set; }
    @AuraEnabled public List<String> choices { get; set; }
    @AuraEnabled public String visibleIf { get; set; }
    @AuraEnabled public Integer maxLength { get; set; }
    @AuraEnabled public Map<String, String> description { get; set; }
    @AuraEnabled public Boolean isRequired { get; set; }
    @AuraEnabled public List<ChoiceWrapper> complexChoices { get; set; }
    @AuraEnabled public Boolean showOtherItem { get; set; }
    @AuraEnabled public Map<String, String> otherPlaceholder { get; set; }
    @AuraEnabled public Map<String, String> otherText { get; set; }
    @AuraEnabled public Integer colCount { get; set; }
    @AuraEnabled public Integer maxSelectedChoices { get; set; }
    @AuraEnabled public Map<String, String> placeholder { get; set; }
    @AuraEnabled public List<ValidatorWrapper> validators { get; set; }
    
    public class ChoiceWrapper {
        @AuraEnabled public String value { get; set; }
        @AuraEnabled public Object text { get; set; } // Can be String or Map<String, String>
    }
    
    public class ValidatorWrapper {
        @AuraEnabled public String type { get; set; }
    }

    public static ElementModel toJson(Element__c record) {
        ElementModel model = new ElementModel();
        model.id = record.Id;
        model.pageId = record.Page__c;
        model.name = record.Name;
        model.type = record.Type__c;
        model.sequence = record.Sequence__c;
        model.body = record.Body__c;
        return model;
    }

    public Element__c toRecord() {
        return new Element__c(
            Id = this.id,
            Page__c = this.pageId,
            Name = this.name,
            Type__c = this.type,
            Sequence__c = this.sequence,
            Body__c = this.body
        );
    }
}