unpackaged/pre/objects/Element__c/Element__c.object-meta.xml
<CustomObject>
    <label>Element</label>
    <nameField>
        <label>Element Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Elements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Element__c/fields/Page__c.field-meta.xml
<CustomField>
    <fullName>Page__c</fullName>
    <label>Page</label>
    <referenceTo>Page__c</referenceTo>
    <relationshipLabel>Elements</relationshipLabel>
    <relationshipName>Elements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Element__c/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <label>Sequence</label>
    <type>Number</type>
    <precision>18</precision>
    <scale>0</scale>
</CustomField>

force-app/main/default/objects/Element__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>rating</fullName>
            </value>
            <value>
                <fullName>dropdown</fullName>
            </value>
            <value>
                <fullName>comment</fullName>
            </value>
            <value>
                <fullName>checkbox</fullName>
            </value>
            <value>
                <fullName>boolean</fullName>
            </value>
            <value>
                <fullName>radiogroup</fullName>
            </value>
            <value>
                <fullName>text</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Page__c/Page__c.object-meta.xml
<CustomObject>
    <label>Page</label>
    <nameField>
        <label>Page Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Page__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <defaultValue>&quot;{}&quot;</defaultValue>
    <label>Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Page__c/fields/SurveyVersion__c.field-meta.xml
<CustomField>
    <fullName>SurveyVersion__c</fullName>
    <label>Survey Version</label>
    <referenceTo>SurveyVersion__c</referenceTo>
    <relationshipLabel>Pages</relationshipLabel>
    <relationshipName>Pages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/pre/objects/SurveyVersion__c/SurveyVersion__c.object-meta.xml
<CustomObject>
    <label>Survey Version</label>
    <nameField>
        <label>Version Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SurveyVersion__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <label>Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/pre/classes/PageService.cls
public with sharing class PageService {
    @AuraEnabled
    public static PageModel getPage(Id pageId) {
        Page__c page = [
            SELECT Id, Name, SurveyVersion__c, Sequence__c, Body__c,
                   (SELECT Id, Name, Type__c, Sequence__c, Body__c 
                    FROM Elements__r 
                    ORDER BY Sequence__c ASC)
            FROM Page__c 
            WHERE Id = :pageId
        ];
        
        PageModel model = PageModel.toJson(page);
        model.elements = new List<ElementModel>();
        
        for(Element__c element : page.Elements__r) {
            model.elements.add(ElementModel.toJson(element));
        }
        
        return model;
    }
    
    @AuraEnabled
    public static PageModel savePage(PageModel model) {
        Page__c page = model.toRecord();
        upsert page;
        
        // Save elements
        if(model.elements != null && !model.elements.isEmpty()) {
            List<Element__c> elements = new List<Element__c>();
            for(ElementModel elementModel : model.elements) {
                Element__c element = elementModel.toRecord();
                element.Page__c = page.Id;
                elements.add(element);
            }
            upsert elements;
        }
        
        return getPage(page.Id);
    }
    
    @AuraEnabled
    public static void deletePage(Id pageId) {
        delete [SELECT Id FROM Page__c WHERE Id = :pageId];
    }
    
    public static List<Page__c> getVersionPages(Id versionId) {
        return [SELECT Id, Name, SurveyVersion__c, Sequence__c, Body__c 
                FROM Page__c 
                WHERE SurveyVersion__c = :versionId 
                ORDER BY Sequence__c ASC];
    }
} 