unpackaged/pre/objects/Element__c/Element__c.object-meta.xml
<CustomObject>
    <label>Element</label>
    <nameField>
        <label>Element Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Elements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Element__c/fields/Page__c.field-meta.xml
<CustomField>
    <fullName>Page__c</fullName>
    <label>Page</label>
    <referenceTo>Page__c</referenceTo>
    <relationshipLabel>Elements</relationshipLabel>
    <relationshipName>Elements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Element__c/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <label>Sequence</label>
    <type>Number</type>
    <precision>18</precision>
    <scale>0</scale>
</CustomField>

force-app/main/default/objects/Element__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>rating</fullName>
            </value>
            <value>
                <fullName>dropdown</fullName>
            </value>
            <value>
                <fullName>comment</fullName>
            </value>
            <value>
                <fullName>checkbox</fullName>
            </value>
            <value>
                <fullName>boolean</fullName>
            </value>
            <value>
                <fullName>radiogroup</fullName>
            </value>
            <value>
                <fullName>text</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Page__c/Page__c.object-meta.xml
<CustomObject>
    <label>Page</label>
    <nameField>
        <label>Page Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Page__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <defaultValue>&quot;{}&quot;</defaultValue>
    <label>Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/pre/classes/ElementService.cls
public with sharing class ElementService {
    @AuraEnabled
    public static ElementModel getElement(Id elementId) {
        Element__c element = [
            SELECT Id, Name, Page__c, Type__c, Sequence__c, Body__c
            FROM Element__c 
            WHERE Id = :elementId
        ];
        
        return ElementModel.toJson(element);
    }
    
    @AuraEnabled
    public static ElementModel saveElement(ElementModel model) {
        Element__c element = model.toRecord();
        upsert element;
        return getElement(element.Id);
    }
    
    @AuraEnabled
    public static void deleteElement(Id elementId) {
        delete [SELECT Id FROM Element__c WHERE Id = :elementId];
    }
    
    public static List<Element__c> getPageElements(Set<Id> pageIds) {
        return [SELECT Id, Name, Page__c, Type__c, Sequence__c, Body__c 
                FROM Element__c 
                WHERE Page__c IN :pageIds 
                ORDER BY Sequence__c ASC];
    }
} 