force-app/main/default/objects/Page__c/Page__c.object-meta.xml
<CustomObject>
    <label>Page</label>
    <nameField>
        <label>Page Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/pre/objects/Page__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField> 

force-app/main/default/objects/Page__c/fields/SurveyVersion__c.field-meta.xml
<CustomField>
    <fullName>SurveyVersion__c</fullName>
    <label>Survey Version</label>
    <referenceTo>SurveyVersion__c</referenceTo>
    <relationshipLabel>Pages</relationshipLabel>
    <relationshipName>Pages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SurveyVersion__c/SurveyVersion__c.object-meta.xml
<CustomObject>
    <label>Survey Version</label>
    <pluralLabel>Survey Versions</pluralLabel>
    <nameField>
        <type>Text</type>
        <label>Version Number</label>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/PageModel.cls
public class PageModel {
    public String recordId;
    public String name;
    public Decimal order;
    public List<ElementModel> elements;
    
    public PageModel() {
        this.elements = new List<ElementModel>();
    }
    
    public Page__c toSObject(Id versionId) {
        Page__c page = new Page__c(
            SurveyVersion__c = versionId,
            Name__c = this.name,
            Order__c = this.order
        );
        return page;
    }
    
    public static PageModel fromSObject(Page__c page) {
        PageModel model = new PageModel();
        model.recordId = page.Id;
        model.name = page.Name__c;
        model.order = page.Order__c;
        return model;
    }
} 