force-app/main/default/objects/Page__c/Page__c.object-meta.xml
<CustomObject>
    <label>Page</label>
    <nameField>
        <label>Page Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Page__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <defaultValue>&quot;{}&quot;</defaultValue>
    <label>Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Page__c/fields/SurveyVersion__c.field-meta.xml
<CustomField>
    <fullName>SurveyVersion__c</fullName>
    <label>Survey Version</label>
    <referenceTo>SurveyVersion__c</referenceTo>
    <relationshipLabel>Pages</relationshipLabel>
    <relationshipName>Pages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SurveyVersion__c/SurveyVersion__c.object-meta.xml
<CustomObject>
    <label>Survey Version</label>
    <pluralLabel>Survey Versions</pluralLabel>
    <nameField>
        <type>Text</type>
        <label>Version Number</label>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SurveyVersion__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <label>Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/models/PageModel.cls
public class PageModel {
    @AuraEnabled public Id id { get; set; }
    @AuraEnabled public Id surveyVersionId { get; set; }
    @AuraEnabled public String name { get; set; }
    @AuraEnabled public Decimal sequence { get; set; }
    @AuraEnabled public String body { get; set; }
    @AuraEnabled public List<ElementModel> elements { get; set; }

    public static PageModel toJson(Page__c page) {
        PageModel model = new PageModel();
        model.id = page.Id;
        model.surveyVersionId = page.SurveyVersion__c;
        model.name = page.Name;
        model.sequence = page.Sequence__c;
        model.body = page.Body__c;
        return model;
    }

    public Page__c toRecord() {
        return new Page__c(
            Id = this.id,
            SurveyVersion__c = this.surveyVersionId,
            Name = this.name,
            Sequence__c = this.sequence,
            Body__c = this.body
        );
    }
}