force-app/main/default/objects/Response__c/Response__c.object-meta.xml
<CustomObject>
    <label>Response</label>
    <nameField>
        <displayFormat>R-{00000}</displayFormat>
        <label>Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Response__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <label>Survey</label>
    <referenceTo>SurveyVersion__c</referenceTo>
    <relationshipLabel>Responses</relationshipLabel>
    <relationshipName>Responses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ResponseElement__c/ResponseElement__c.object-meta.xml
<CustomObject>
    <label>Response Element</label>
    <nameField>
        <displayFormat>RE-{00000}</displayFormat>
        <label>Response Element Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Response Elements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ResponseElement__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <label>Response</label>
    <referenceTo>Response__c</referenceTo>
    <relationshipLabel>Elements</relationshipLabel>
    <relationshipName>Elements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Survey__c/Survey__c.object-meta.xml
<CustomObject>
    <label>Survey</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Survey Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ResponseDTO.cls
public class ResponseDTO {
    @AuraEnabled public Id id { get; set; }
    @AuraEnabled public String name { get; set; }
    @AuraEnabled public String body { get; set; }
    @AuraEnabled public String createdBy { get; set; }
    @AuraEnabled public String lastModifiedBy { get; set; }
    @AuraEnabled public Id surveyVersionId { get; set; }
    @AuraEnabled public List<ResponseElementDTO> responseElements { get; set; }
    
    public ResponseDTO(Response__c response, List<ResponseElement__c> responseElements) {
        this.id = response.Id;
        this.name = response.Name;
        this.body = response.Body__c;
        this.createdBy = response.CreatedBy.Name;
        this.lastModifiedBy = response.LastModifiedBy.Name;
        this.surveyVersionId = response.Survey__c;
        this.responseElements = new List<ResponseElementDTO>();
        for (ResponseElement__c re : responseElements) {
            this.responseElements.add(new ResponseElementDTO(re));
        }
    }
}