force-app/main/default/objects/ElementVersion__c/ElementVersion__c.object-meta.xml
<CustomObject>
    <label>Element Version</label>
    <nameField>
        <displayFormat>EV-{00000}</displayFormat>
        <label>Element Version Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Element Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Response__c/Response__c.object-meta.xml
<CustomObject>
    <label>Response</label>
    <nameField>
        <displayFormat>R-{00000}</displayFormat>
        <label>Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ResponseElement__c/ResponseElement__c.object-meta.xml
<CustomObject>
    <label>Response Element</label>
    <nameField>
        <displayFormat>RE-{00000}</displayFormat>
        <label>Response Element Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Response Elements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ResponseElement__c/fields/ElementVersion__c.field-meta.xml
<CustomField>
    <fullName>ElementVersion__c</fullName>
    <label>Element Version</label>
    <referenceTo>ElementVersion__c</referenceTo>
    <relationshipLabel>Responses</relationshipLabel>
    <relationshipName>Responses</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ResponseElement__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <label>Response</label>
    <referenceTo>Response__c</referenceTo>
    <relationshipLabel>Elements</relationshipLabel>
    <relationshipName>Elements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ResponseElementDTO.cls
public class ResponseElementDTO {
    @AuraEnabled public Id id { get; set; }
    @AuraEnabled public String body { get; set; }
    @AuraEnabled public Id elementId { get; set; }
    @AuraEnabled public Id responseId { get; set; }
    
    public ResponseElementDTO(Id id, String body, Id elementId, Id responseId) {
        this.id = id;
        this.body = body;
        this.elementId = elementId;
        this.responseId = responseId;
    }
    
    public ResponseElementDTO(ResponseElement__c responseElement) {
        this(responseElement.Id, responseElement.Body__c, responseElement.ElementVersion__c, responseElement.Response__c);
    }
    
    // Constructor for creating new response elements
    public ResponseElementDTO(String body, Id elementId) {
        this(null, body, elementId, null);
    }
}