force-app/main/default/objects/ElementVersion__c/ElementVersion__c.object-meta.xml
<CustomObject>
    <label>Element Version</label>
    <nameField>
        <displayFormat>EV-{00000}</displayFormat>
        <label>Element Version Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Element Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Response__c/Response__c.object-meta.xml
<CustomObject>
    <label>Response</label>
    <nameField>
        <displayFormat>R-{00000}</displayFormat>
        <label>Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Response__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <label>Survey</label>
    <referenceTo>SurveyVersion__c</referenceTo>
    <relationshipLabel>Responses</relationshipLabel>
    <relationshipName>Responses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ResponseElement__c/ResponseElement__c.object-meta.xml
<CustomObject>
    <label>Response Element</label>
    <nameField>
        <displayFormat>RE-{00000}</displayFormat>
        <label>Response Element Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Response Elements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ResponseElement__c/fields/ElementVersion__c.field-meta.xml
<CustomField>
    <fullName>ElementVersion__c</fullName>
    <label>Element Version</label>
    <referenceTo>ElementVersion__c</referenceTo>
    <relationshipLabel>Responses</relationshipLabel>
    <relationshipName>Responses</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ResponseElement__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <label>Response</label>
    <referenceTo>Response__c</referenceTo>
    <relationshipLabel>Elements</relationshipLabel>
    <relationshipName>Elements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Survey__c/Survey__c.object-meta.xml
<CustomObject>
    <label>Survey</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Survey Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ResponseService.cls
public class ResponseService {
    private ResponseRepository responseRepo;
    private ResponseElementRepository responseElementRepo;
    
    public ResponseService() {
        this.responseRepo = new ResponseRepository();
        this.responseElementRepo = new ResponseElementRepository();
    }
    
    public ResponseDTO getResponseWithElements(Id responseId) {
        Response__c response = responseRepo.getResponseById(responseId);
        List<ResponseElement__c> responseElements = responseElementRepo.getResponseElementsByResponseId(responseId);
        return new ResponseDTO(response, responseElements);
    }
    
    public List<ResponseDTO> getResponsesBySurveyVersionId(Id surveyVersionId) {
        List<ResponseDTO> responseDTOs = new List<ResponseDTO>();
        for (Response__c response : responseRepo.getResponsesBySurveyVersionId(surveyVersionId)) {
            List<ResponseElement__c> responseElements = responseElementRepo.getResponseElementsByResponseId(response.Id);
            responseDTOs.add(new ResponseDTO(response, responseElements));
        }
        return responseDTOs;
    }
    
    public void createResponse(String responseBody, Id surveyVersionId, List<ResponseElementDTO> responseElements) {
        Response__c newResponse = new Response__c(
            Body__c = responseBody,
            Survey__c = surveyVersionId
        );
        responseRepo.createResponse(newResponse);
        
        List<ResponseElement__c> newResponseElements = new List<ResponseElement__c>();
        for (ResponseElementDTO reDTO : responseElements) {
            newResponseElements.add(new ResponseElement__c(
                Body__c = reDTO.body,
                ElementVersion__c = reDTO.elementId,
                Response__c = newResponse.Id
            ));
        }
        responseElementRepo.createResponseElement(newResponseElements);
    }
}