force-app/main/default/objects/ElementVersion__c/ElementVersion__c.object-meta.xml
<CustomObject>
    <label>Element Version</label>
    <nameField>
        <displayFormat>EV-{00000}</displayFormat>
        <label>Element Version Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Element Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Response__c/Response__c.object-meta.xml
<CustomObject>
    <label>Response</label>
    <nameField>
        <displayFormat>R-{00000}</displayFormat>
        <label>Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ResponseElement__c/ResponseElement__c.object-meta.xml
<CustomObject>
    <label>Response Element</label>
    <nameField>
        <displayFormat>RE-{00000}</displayFormat>
        <label>Response Element Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Response Elements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ResponseElement__c/fields/ElementVersion__c.field-meta.xml
<CustomField>
    <fullName>ElementVersion__c</fullName>
    <label>Element Version</label>
    <referenceTo>ElementVersion__c</referenceTo>
    <relationshipLabel>Responses</relationshipLabel>
    <relationshipName>Responses</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ResponseElement__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <label>Response</label>
    <referenceTo>Response__c</referenceTo>
    <relationshipLabel>Elements</relationshipLabel>
    <relationshipName>Elements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ResponseElementRepository.cls
public class ResponseElementRepository {
    public List<ResponseElement__c> getResponseElementsByResponseId(Id responseId) {
        return [SELECT Id, Body__c, CreatedBy.Name, LastModifiedBy.Name, ElementVersion__c, Response__c
                FROM ResponseElement__c
                WHERE Response__c = :responseId];
    }
    
    public void createResponseElement(List<ResponseElement__c> responseElements) {
        insert responseElements;
    }
    
    public void updateResponseElement(ResponseElement__c responseElement) {
        update responseElement;
    }
    
    public void deleteResponseElement(Id responseElementId) {
        delete [SELECT Id FROM ResponseElement__c WHERE Id = :responseElementId];
    }
}