force-app/main/default/objects/Element__c/Element__c.object-meta.xml
<CustomObject>
    <label>Element</label>
    <nameField>
        <displayFormat>E-{00000}</displayFormat>
        <label>Element Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Elements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Element__c/fields/Page__c.field-meta.xml
<CustomField>
    <fullName>Page__c</fullName>
    <label>Page</label>
    <referenceTo>Page__c</referenceTo>
    <relationshipLabel>Elements</relationshipLabel>
    <relationshipName>Elements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Page__c/Page__c.object-meta.xml
<CustomObject>
    <label>Page</label>
    <nameField>
        <label>Page Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/pre/objects/Page__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField> 

force-app/main/default/classes/PageService.cls
public class PageService {
    public static PageModel createPage(PageModel model, Id versionId) {
        Page__c page = model.toSObject(versionId);
        insert page;
        
        for(ElementModel element : model.elements) {
            Element__c elementObj = element.toSObject(page.Id);
            insert elementObj;
        }
        
        return PageModel.fromSObject(page);
    }
    
    public static void updatePageOrder(Id pageId, Decimal newOrder) {
        Page__c page = [SELECT Id, Order__c FROM Page__c WHERE Id = :pageId];
        page.Order__c = newOrder;
        update page;
    }
    
    public static void deletePage(Id pageId) {
        // Delete all elements first
        List<Element__c> elements = [SELECT Id FROM Element__c WHERE Page__c = :pageId];
        delete elements;
        
        // Then delete the page
        Page__c page = [SELECT Id FROM Page__c WHERE Id = :pageId];
        delete page;
    }
} 