force-app/main/default/objects/Element__c/Element__c.object-meta.xml
<CustomObject>
    <label>Element</label>
    <nameField>
        <displayFormat>E-{00000}</displayFormat>
        <label>Element Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Elements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ElementVersion__c/ElementVersion__c.object-meta.xml
<CustomObject>
    <label>Element Version</label>
    <nameField>
        <displayFormat>EV-{00000}</displayFormat>
        <label>Element Version Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Element Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ElementVersion__c/fields/Element__c.field-meta.xml
<CustomField>
    <fullName>Element__c</fullName>
    <label>Element</label>
    <referenceTo>Element__c</referenceTo>
    <relationshipLabel>Versions</relationshipLabel>
    <relationshipName>Versions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ElementService.cls
public class ElementService {
    private ElementRepository elementRepo;
    private ElementVersionRepository elementVersionRepo;
    
    public ElementService() {
        this.elementRepo = new ElementRepository();
        this.elementVersionRepo = new ElementVersionRepository();
    }
    
    public ElementDTO getElementWithLatestVersion(Id elementId) {
        Element__c element = elementRepo.getElementById(elementId);
        ElementVersion__c latestVersion = elementVersionRepo.getLatestVersionByElementId(elementId);
        return new ElementDTO(element, latestVersion);
    }
    
    public List<ElementDTO> getAllElementsWithLatestVersions() {
        List<ElementDTO> elementDTOs = new List<ElementDTO>();
        for (Element__c element : elementRepo.getAllElements()) {
            ElementVersion__c latestVersion = elementVersionRepo.getLatestVersionByElementId(element.Id);
            elementDTOs.add(new ElementDTO(element, latestVersion));
        }
        return elementDTOs;
    }
    
    public Id createElementWithVersion(String elementBody) {
        Element__c newElement = new Element__c();
        Id elementId = elementRepo.createElement(newElement);
        
        ElementVersion__c newVersion = new ElementVersion__c(
            Element__c = elementId,
            Body__c = elementBody
        );
        return elementVersionRepo.createElementVersion(newVersion);
    }
    
    public Id updateElementVersion(Id elementId, String newElementBody) {
        ElementVersion__c newVersion = new ElementVersion__c(
            Element__c = elementId,
            Body__c = newElementBody
        );
        return elementVersionRepo.createElementVersion(newVersion);
    }
}