force-app/main/default/objects/Element__c/Element__c.object-meta.xml
<CustomObject>
    <label>Element</label>
    <nameField>
        <displayFormat>E-{00000}</displayFormat>
        <label>Element Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Elements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ElementVersion__c/ElementVersion__c.object-meta.xml
<CustomObject>
    <label>Element Version</label>
    <nameField>
        <displayFormat>EV-{00000}</displayFormat>
        <label>Element Version Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Element Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ElementVersion__c/fields/Element__c.field-meta.xml
<CustomField>
    <fullName>Element__c</fullName>
    <label>Element</label>
    <referenceTo>Element__c</referenceTo>
    <relationshipLabel>Versions</relationshipLabel>
    <relationshipName>Versions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ElementVersionRepository.cls
public class ElementVersionRepository {
    public Id createElementVersion(ElementVersion__c elementVersion) {
        insert elementVersion;
        return elementVersion.Id;
    }
    
    public ElementVersion__c getLatestVersionByElementId(Id elementId) {
        return [SELECT Id, Name, Body__c, CreatedBy.Name, LastModifiedBy.Name, Element__c
                FROM ElementVersion__c
                WHERE Element__c = :elementId
                ORDER BY CreatedDate DESC
                LIMIT 1];
    }
    
    public List<ElementVersion__c> getAllVersionsByElementId(Id elementId) {
        return [SELECT Id, Name, Body__c, CreatedBy.Name, LastModifiedBy.Name, Element__c
                FROM ElementVersion__c
                WHERE Element__c = :elementId
                ORDER BY CreatedDate DESC];
    }
}