force-app/main/default/objects/Element__c/Element__c.object-meta.xml
<CustomObject>
    <label>Element</label>
    <nameField>
        <displayFormat>E-{00000}</displayFormat>
        <label>Element Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Elements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ElementVersion__c/ElementVersion__c.object-meta.xml
<CustomObject>
    <label>Element Version</label>
    <nameField>
        <displayFormat>EV-{00000}</displayFormat>
        <label>Element Version Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Element Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ElementVersion__c/fields/Element__c.field-meta.xml
<CustomField>
    <fullName>Element__c</fullName>
    <label>Element</label>
    <referenceTo>Element__c</referenceTo>
    <relationshipLabel>Versions</relationshipLabel>
    <relationshipName>Versions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ElementDTO.cls
public class ElementDTO {
    @AuraEnabled public Id id { get; set; }
    @AuraEnabled public String name { get; set; }
    @AuraEnabled public String createdBy { get; set; }
    @AuraEnabled public String lastModifiedBy { get; set; }
    @AuraEnabled public String owner { get; set; }
    @AuraEnabled public Id latestVersionId { get; set; }
    @AuraEnabled public String latestVersionBody { get; set; }
    
    public ElementDTO(Element__c element, ElementVersion__c latestVersion) {
        this.id = element.Id;
        this.name = element.Name;
        this.createdBy = element.CreatedBy.Name;
        this.lastModifiedBy = element.LastModifiedBy.Name;
        this.owner = element.Owner.Name;
        
        if (latestVersion != null) {
            this.latestVersionId = latestVersion.Id;
            this.latestVersionBody = latestVersion.Body__c;
        }
    }
}