force-app/main/default/objects/Survey__c/Survey__c.object-meta.xml
<CustomObject>
    <label>Survey</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Survey Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField> 

force-app/main/default/objects/SurveyVersion__c/SurveyVersion__c.object-meta.xml
<CustomObject>
    <label>Survey Version</label>
    <pluralLabel>Survey Versions</pluralLabel>
    <nameField>
        <type>Text</type>
        <label>Version Number</label>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SurveyVersion__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <label>Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SurveyVersion__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <label>Survey</label>
    <referenceTo>Survey__c</referenceTo>
    <relationshipLabel>Survey Versions</relationshipLabel>
    <relationshipName>Versions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SurveyVersion__c/fields/VersionNumber__c.field-meta.xml
<CustomField>
    <fullName>VersionNumber__c</fullName>
    <label>Version Number</label>
    <type>Text</type>
    <length>255</length>
</CustomField>

force-app/main/default/classes/SurveyBuilderController.cls
public with sharing class SurveyBuilderController {
    @AuraEnabled
    public static String saveSurvey(String jsonString) {
        try {
            return SurveyService.saveAndEnrichJson(jsonString);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    @AuraEnabled
    public static String getLatestVersion(Id surveyId) {
        try {
            return SurveyService.getLatestVersionJson(surveyId);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    @AuraEnabled
    public static String getVersionById(Id versionId) {
        try {
            return SurveyService.getVersionJson(versionId);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    // POC below - Demo purpose only
    @AuraEnabled
    public static String saveSurveyPOC(String surveyId, String jsonString) {
        try {
            // This is just POC code to save the survey. If survey is already present, it will create a new version.
            Map<String, Object> jsonMap = (Map<String, Object>) JSON.deserializeUntyped(jsonString);
            string surveyTitle = String.valueOf(jsonMap.get('title'));

            if(surveyId == null || surveyId == '') {
                Survey__c survey = new Survey__c();
                survey.Title__c = surveyTitle;
                insert survey;
                SurveyVersion__c surveyVersion = new SurveyVersion__c();
                surveyVersion.Survey__c = survey.Id;
                surveyVersion.VersionNumber__c = 1;
                surveyVersion.Body__c = jsonString;
                insert surveyVersion;
            }
            else {
                List<Survey__c> existingSurveys = [SELECT Id
                                                FROM Survey__c 
                                                WHERE Id = :surveyId LIMIT 1];
                if(existingSurveys != null && existingSurveys.size() > 0) {
                    AggregateResult[] latestVersion = [SELECT MAX(VersionNumber__c) latestVersion 
                                                        FROM SurveyVersion__c 
                                                        WHERE Survey__c = :surveyId];
                    Decimal latestVersionNumber = latestVersion != null && latestVersion.size() > 0 
                                                    ? (Decimal) latestVersion[0].get('latestVersion')
                                                    : 0;

                    SurveyVersion__c surveyVersion = new SurveyVersion__c();
                    surveyVersion.Survey__c = surveyId;
                    surveyVersion.VersionNumber__c = latestVersionNumber + 1;
                    surveyVersion.Body__c = jsonString;
                    insert surveyVersion;
                }
                else {
                    Survey__c survey = new Survey__c();
                    survey.Title__c = surveyTitle;
                    insert survey;
                    SurveyVersion__c surveyVersion = new SurveyVersion__c();
                    surveyVersion.Survey__c = survey.Id;
                    surveyVersion.VersionNumber__c = 1;
                    surveyVersion.Body__c = jsonString;
                    insert surveyVersion;
                }
            }
            return jsonString;
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    @AuraEnabled
    public static String getLatestVersionBySurveyIdPOC(Id surveyId) {
        try {
            SurveyVersion__c surveyVersion = [SELECT Id, Body__c 
                                                FROM SurveyVersion__c 
                                                WHERE Survey__c = :surveyId 
                                                ORDER BY VersionNumber__c DESC LIMIT 1];
            return surveyVersion.Body__c;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    @AuraEnabled
    public static String getVersionByIdPOC(Id surveyVersionId) {
        try {
            SurveyVersion__c surveyVersion = [SELECT Id, Body__c 
                                                FROM SurveyVersion__c 
                                                WHERE Id = :surveyVersionId 
                                                LIMIT 1];
            return surveyVersion.Body__c;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
} 