force-app/main/default/objects/Survey__c/Survey__c.object-meta.xml
<CustomObject>
    <label>Survey</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Survey Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Response__c/Survey_Response__c.object-meta.xml
<CustomObject>
    <label>Survey Response</label>
    <nameField>
        <displayFormat>SR - {000000}</displayFormat>
        <label>Survey Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Response__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <label>Body</label>
    <length>130000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Survey_Response__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <label>Survey</label>
    <referenceTo>Survey__c</referenceTo>
    <relationshipLabel>Survey Responses</relationshipLabel>
    <relationshipName>Survey_Responses</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SurveyTaker.cls
public without sharing class SurveyTaker {

    @AuraEnabled
    public static Map<String,String> fetchSurvey(String encryptedId){
        encryptedId = encryptedId.replaceAll(' ','+');
        try {
            // decrypt the encrypted id 
            // it is encrypted with the crypto decryption method
            Blob surveyId = EncodingUtil.base64Decode(encryptedId);
            Blob decryptedSurveyId = Crypto.decryptWithManagedIV('AES256', Blob.valueOf(System.Label.Survey_Encryption_Key), surveyId);
            String surveyIdString = decryptedSurveyId.toString();

            Map<String,String> resMap = SurveyBuilder.getSurveyVersion(surveyIdString);
          
            return new Map<String,String>{'version' => resMap.get('version')};
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

       @AuraEnabled
    public static void saveResponse(String response,Id recId){
        try {
            insert new Survey_Response__c(Body__c=response,Survey__c = recId);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    
}