force-app/main/default/objects/Survey__c/Survey__c.object-meta.xml
<CustomObject>
    <label>Survey</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Survey Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey__c/fields/ActiveVersion__c.field-meta.xml
<CustomField>
    <fullName>ActiveVersion__c</fullName>
    <label>Active Version</label>
    <referenceTo>SurveyVersion__c</referenceTo>
    <relationshipLabel>Active Surveys</relationshipLabel>
    <relationshipName>ActiveSurveys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField> 

force-app/main/default/classes/models/SurveyModel.cls
public class SurveyModel {
    @AuraEnabled public Id id { get; set; }
    @AuraEnabled public String title { get; set; }
    @AuraEnabled public String description { get; set; }
    @AuraEnabled public Id activeVersionId { get; set; }
    @AuraEnabled public List<SurveyVersionModel> versions { get; set; }

    public static SurveyModel toJson(Survey__c survey) {
        SurveyModel model = new SurveyModel();
        model.id = survey.Id;
        model.title = survey.Name;
        model.activeVersionId = survey.ActiveVersion__c;
        return model;
    }

    public Survey__c toRecord() {
        Survey__c record = new Survey__c(
            Id = this.id,
            Name = this.title,
            ActiveVersion__c = this.activeVersionId,
            Description__c = this.description
        );
        return record;
    }
}