force-app/main/default/objects/Survey__c/Survey__c.object-meta.xml
<CustomObject>
    <label>Survey</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Survey Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SurveyVersion__c/SurveyVersion__c.object-meta.xml
<CustomObject>
    <label>Survey Version</label>
    <pluralLabel>Survey Versions</pluralLabel>
    <nameField>
        <type>Text</type>
        <label>Version Number</label>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SurveyVersion__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <label>Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SurveyVersion__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <label>Survey</label>
    <referenceTo>Survey__c</referenceTo>
    <relationshipLabel>Survey Versions</relationshipLabel>
    <relationshipName>Versions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SurveyVersionRepository.cls
public class SurveyVersionRepository {
    public SurveyVersion__c getLatestVersionBySurveyId(Id surveyId) {
        return [SELECT Id, Name, Body__c, CreatedBy.Name, LastModifiedBy.Name, Survey__c
                FROM SurveyVersion__c
                WHERE Survey__c = :surveyId
                ORDER BY CreatedDate DESC
                LIMIT 1];
    }
    
    public List<SurveyVersion__c> getAllVersionsBySurveyId(Id surveyId) {
        return [SELECT Id, Name, Body__c, CreatedBy.Name, LastModifiedBy.Name, Survey__c
                FROM SurveyVersion__c
                WHERE Survey__c = :surveyId
                ORDER BY CreatedDate DESC];
    }
    
    public void createSurveyVersion(SurveyVersion__c surveyVersion) {
        insert surveyVersion;
    }
    
    public void updateSurveyVersion(SurveyVersion__c surveyVersion) {
        update surveyVersion;
    }
}