force-app/main/default/objects/Survey__c/Survey__c.object-meta.xml
<CustomObject>
    <label>Survey</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Survey Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SurveyVersion__c/SurveyVersion__c.object-meta.xml
<CustomObject>
    <label>Survey Version</label>
    <pluralLabel>Survey Versions</pluralLabel>
    <nameField>
        <type>Text</type>
        <label>Version Number</label>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SurveyVersion__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField> 

force-app/main/default/objects/SurveyVersion__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <label>Survey</label>
    <referenceTo>Survey__c</referenceTo>
    <relationshipLabel>Survey Versions</relationshipLabel>
    <relationshipName>Versions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SurveyVersion__c/fields/VersionNumber__c.field-meta.xml
<CustomField>
    <fullName>VersionNumber__c</fullName>
    <label>Version Number</label>
    <type>Text</type>
    <length>255</length>
</CustomField>

force-app/main/default/classes/SurveyVersionModel.cls
public class SurveyVersionModel {
    public String recordId;
    public Decimal versionNumber;
    public Boolean isActive;
    public List<PageModel> pages;
    
    public SurveyVersionModel() {
        this.pages = new List<PageModel>();
    }
    
    public SurveyVersion__c toSObject(Id surveyId) {
        SurveyVersion__c version = new SurveyVersion__c(
            Survey__c = surveyId,
            VersionNumber__c = this.versionNumber,
            IsActive__c = this.isActive
        );
        return version;
    }
    
    public static SurveyVersionModel fromSObject(SurveyVersion__c version) {
        SurveyVersionModel model = new SurveyVersionModel();
        model.recordId = version.Id;
        model.versionNumber = version.VersionNumber__c;
        model.isActive = version.IsActive__c;
        return model;
    }
} 