force-app/main/default/objects/Survey__c/Survey__c.object-meta.xml
<CustomObject>
    <label>Survey</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Survey Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField> 

force-app/main/default/objects/Survey__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField> 

force-app/main/default/objects/Survey__c/fields/Width__c.field-meta.xml
<CustomField>
    <fullName>Width__c</fullName>
    <label>Width</label>
    <length>10</length>
    <type>Text</type>
</CustomField> 

force-app/main/default/objects/Survey__c/fields/WidthMode__c.field-meta.xml
<CustomField>
    <fullName>WidthMode__c</fullName>
    <label>Width Mode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>static</fullName>
                <default>true</default>
            </value>
            <value>
                <fullName>responsive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField> 

force-app/main/default/classes/SurveyModel.cls
public class SurveyModel {
    public String recordId;
    public String title;
    public String description;
    public String widthMode;
    public String width;
    public List<SurveyVersionModel> versions;
    
    public SurveyModel() {
        this.versions = new List<SurveyVersionModel>();
    }
    
    public Survey__c toSObject() {
        Survey__c survey = new Survey__c(
            Title__c = this.title,
            Description__c = this.description,
            WidthMode__c = this.widthMode,
            Width__c = this.width
        );
        return survey;
    }
    
    public static SurveyModel fromSObject(Survey__c survey) {
        SurveyModel model = new SurveyModel();
        model.recordId = survey.Id;
        model.title = survey.Title__c;
        model.description = survey.Description__c;
        model.widthMode = survey.WidthMode__c;
        model.width = survey.Width__c;
        return model;
    }
} 