unpackaged/pre/objects/Survey__c/Survey__c.object-meta.xml
<CustomObject>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/pre/objects/SurveyVersion__c/SurveyVersion__c.object-meta.xml
<CustomObject>
    <label>Survey Version</label>
    <nameField>
        <label>Version Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SurveyVersion__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <label>Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SurveyVersion__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SurveyVersion__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <label>Survey</label>
    <referenceTo>Survey__c</referenceTo>
    <relationshipLabel>Survey Versions</relationshipLabel>
    <relationshipName>Versions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/pre/objects/SurveyVersion__c/fields/Version__c.field-meta.xml
<CustomField>
    <fullName>Version__c</fullName>
    <defaultValue>0.1</defaultValue>
    <label>Version</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/pre/classes/SurveyVersionModel.cls
public class SurveyVersionModel {
    @AuraEnabled public Id id { get; set; }
    @AuraEnabled public Id surveyId { get; set; }
    @AuraEnabled public String name { get; set; }
    @AuraEnabled public Decimal version { get; set; }
    @AuraEnabled public String status { get; set; }
    @AuraEnabled public String body { get; set; }
    @AuraEnabled public List<PageModel> pages { get; set; }
    
    public static SurveyVersionModel toJson(SurveyVersion__c record) {
        SurveyVersionModel model = new SurveyVersionModel();
        model.id = record.Id;
        model.surveyId = record.Survey__c;
        model.name = record.Name;
        model.version = record.Version__c;
        model.status = record.Status__c;
        model.body = record.Body__c;
        return model;
    }
    
    public SurveyVersion__c toRecord() {
        return new SurveyVersion__c(
            Id = this.id,
            Survey__c = this.surveyId,
            Name = this.name,
            Version__c = this.version,
            Status__c = this.status,
            Body__c = this.body
        );
    }
} 