force-app/main/default/objects/SurveyVersion__c/SurveyVersion__c.object-meta.xml
<CustomObject>
    <label>Survey Version</label>
    <pluralLabel>Survey Versions</pluralLabel>
    <nameField>
        <type>Text</type>
        <label>Version Number</label>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/pre/objects/SurveyVersion__c/fields/Version__c.field-meta.xml
<CustomField>
    <fullName>Version__c</fullName>
    <defaultValue>0.1</defaultValue>
    <label>Version</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SurveyBuilder.cls
public with sharing class SurveyBuilder {

    @AuraEnabled
    public static void createSurveyFromJSON(String jsonString,SurveyVersion__c surveyVersion, Boolean isUpdate){
        try {
            if(isUpdate){
                // surveyVersion.Version__c--;
                // code here to delete all the elements and pages first and then call SurveyJsService.createSurveyFromJson
            }
        
            SurveyJsService.createSurveyFromJson(jsonString,surveyVersion,isUpdate);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
       
    @AuraEnabled
    public static SurveyVersionDTO.BaseSurveyVersionDTO getSurveyVersion(Id recId){
        try {
            return SurveyVersionController.getSurveyVersionById(recId);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}